apiVersion: v1
kind: Namespace
metadata:
  name: vws-unixsocket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vws-unixsocket
  namespace: vws-unixsocket
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: vws-unixsocket
  template:
    metadata:
      labels:
        app: vws-unixsocket
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: vws-unixsocket
        image: welasco/unixsocket
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: unixSocket
          value: /tmp/socket/server.sock
        - name: clientUnixSocket
          value: /tmp/socket/server2.sock
        volumeMounts:
        - mountPath: /tmp/socket
          name: plugin-dir
      - name: vws-unixsocket2
        image: welasco/unixsocket
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: unixSocket
          value: /tmp/socket/server2.sock
        - name: clientUnixSocket
          value: /tmp/socket/server.sock
        volumeMounts:
        - mountPath: /tmp/socket
          name: plugin-dir
      volumes:
      - hostPath:
          path: /tmp/socket/
          type: DirectoryOrCreate
        name: plugin-dir